### ISSUE TITLE
gfx1036 support?

### ISSUE THREAD

**Issue by jeroen-mostert** [lamikr/rocm_sdk_builder#103]
According to the README and some patches, gfx1036 (the Raphael iGPU found in Ryzen 7000s) should be supported, but it doesn't seem to be. Building RocBLAS + Tensile fails with "architecture not supported", and indeed there is no patch for gfx1036 the way there is for gfx1035, which has many more patched bits.

The repro for this is a `build_cfg.user` with `gfx1030\ngfx1036\ngfx1102` (resulting in `--architecture=gfx1030_gfx1036_gfx1102`) using the latest master and a fresh build.

Adding it in an analogous fashion to rocBLAS with a dumb copy-paste is not hard, but eventually the build then fails for `TensileCreateLibrary` on copying the `TensileLibrary_lazy_gfx1036.dat` file, since there is no such file. No error is present to indicate why this file isn't there (the `_lazy_gfx*.dat` for the other configs are there, as are all the individual `.hsaco` files).

I'm fine with muddling through on this on my own, but some hints on what's needed (if possible) would be nice. If something needs to be patched way before rocBLAS/Tensile, for example, I could be messing around in the wrong place for quite a while.

**Comment by lamikr** [comment]
I need to do similar type of work for gfx1103 so I can try to help you, unfortunately I am busy for couple of next couple of days. For starters you could try to grep my 1035 from my patches.

These APU's are litte different than other GPU's because they share the memory with the CPU. With old rocm versions, when I tested the 2400g apu, I needed to add some patches to kernel also to support allocating memory for kernels. (+ track and report the memory used and available) . Luckily that seems not to be needed anymore.
(Have not tried to use the 2400g for a long time for ml, it did not really speed up much things but at time I thought it would be a cheap hw for teaching purposes anyway to learn how to use hipcc, opencl, etc.)

**Comment by lamikr** [comment]
And first thing is to check that hipcc/clang works for very small apps that creates GPU kernel and communicates with the userspace. For example this one: docs/examples/hipcc/hello_world

**Comment by jeroen-mostert** [comment]
Yeah, I've been testing with `HSA_OVERRIDE_GFX_VERSION=10.3.0`. This also allows gfx1036 to work with the gfx1030 build (at least for BLAS purposes). But this doesn't meaningfully work for most offloading because anything that needs a significant amount of RAM is still slow as molasses. In fact on my machine everything (not just the GPU task) grinds to a halt while the AMD kernel driver is playing around with memory. The iGPU reports a fixed amount of memory (the usual reservation setup), but this memory isn't actually used (or at least it's not reported as used).

It's not completely useless; the single iGPU on my 7600 can match the performance of the CPU for simple things like prompt processing (at a far better energy cost). But if you make the mistake of not disabling it in a multi-GPU setup, the resources will be divided "equally", meaning the iGPU becomes an enormous drag on any discrete GPU you have. You would need a very specific setup to offload particular tasks to targeted devices, which is something most applications understandably don't bother with.

This means it's not really meaningful to sink a lot of time in getting things to work specifically for the model if the override will do just as well for the single GPU case. People who want to use the iGPU for demo purposes (or just to accelerate prompt processing) can make do with the override setting. For other scenarios trying to get the iGPU involved will not help matters.

As such I'm closing this ticket. We can update the docs to mention that the override setting works for this scenario, that's probably enough.

**Comment by lamikr** [comment]
Yes, at least for now it's very specific scenarios for the iGPU but those exist. I was actually thinking today in my background that I should re-investigate the memory transfer from userspace to kernel space and there to igpu and back.

**Comment by jeroen-mostert** [comment]
Yes, not to imply iGPUs are useless, of course, they just have very specific use cases. A relatively weak CPU benefits tremendously from being able to offload to the iGPU, especially if the iGPU is not nerfed, like in laptop setups with mobile graphics. In the case of my Ryzen 5 7600, however, the iGPU has only 2 CUs, and is about on par with the CPU plowing along at 6 threads for a BLAS task of prompt processing. That's still very impressive, especially if you can use both together, it just turned out to be not particularly useful for me, negating my motivation to build model-specific support (which you want in a multi-GPU setup if your iGPU and any discrete GPUs you have are not the same, and thus `HSA_OVERRIDE_GFX_VERSION` will break or nerf things).

**Comment by lamikr** [comment]
I open this issue as I am adding some patches for this while working same time support for gfx1103.

**Comment by jeroen-mostert** [comment]
Re: RAM offloading, I was testing with llama.cpp (or a close offshoot, in any case) and it has a setting (not enabled by default) to use UMA (`hipHostMalloc`), so no copying needs to happen. This can speed things up in some scenarios and is something I imagine other applications can also benefit from, if they are aware of the setup. For dGPUs this is a bad choice, so the appropriate allocation strategy needs to be picked with care. Doubly so in a mixed setup.

**Comment by lamikr** [comment]
That's interesting. Wondering how to handle the UMA in my Framework laptop case where I have both the discrete 7700S and phoenix apu Did you got the llama.cpp working.

Btw, I need to push new version of patches for 1036 and gfx1035 one more time. onnxruntime downloads and builds own version of composable kernel and I need to add a patch to onnxruntime that it then uses to patch the composable_kernel :-) If you have build ongoing, based on to latest patches, no need for clean restart as only the onnxruntime patches gets now updated.

**Comment by jeroen-mostert** [comment]
At present the iGPU on my system is disabled to squeeze every last bit of memory and perf out of the rest of it, but I will re-enable it and do a fresh build of everything tomorrow. The llama.cpp setting seems to apply for all GPUs at the same time (which is odd because it does check for UMA capacity per-device) so I'm interested to see if more tweaking is possible there. On my system combining the iGPU and the dGPU probably doesn't make a whole lot of sense performance-wise but it's still fun to play with. :P

**Comment by jeroen-mostert** [comment]
On a minor note (very minor, since I don't think the internal names are used anywhere), the code name for gfx1036 should be Raphael, same as the 7600 desktop processors. gfx1035 (Rembrandt) is Zen 3+. Of course it's actually all RDNA 2 under the covers (except that gfx1036 is nerfed at 2 CUs).

**Comment by lamikr** [comment]
Thanks, I will change that to Raphael. I have not found myself either any place that would use those codenames.
Usually the gfx* is used, sometimes they may +/- xnack to name to identify whether xnask is used or not.

Aotriton is some kind outlier and uses somewhere in the code real product names "7900 xt", etc. instead of gfx-naming,
