### ISSUE TITLE
torch installs as 2.3.0a0+gitsomething

### ISSUE THREAD

**Issue by jeroen-mostert** [lamikr/rocm_sdk_builder#105]
The pytorch build contains funny logic for automatically determining the version number. Unfortunately this logic falls flat on its face after we're done patching it, causing it to not find the latest tag and be installed as one version less than what it actually is. Needless to say this causes problems when dependencies need to be installed by external packages and pip "helpfully" uninstalls our "old" version to replace it with the "new" one.

We need to fix the versioning logic (or completely override it) so that, at the very least, our package becomes torch-2.3.1 per the latest tag, regardless of how we patched it. Another thing to look into is whether it's possible for us to make it so that certain fundamental packages (like pytorch) cannot be uninstalled or upgraded by vanilla pip at all outside a venv, at least not when dependencies are being satisfied, no matter what the local requirements say, because this is basically never what we want for a custom ROCm build as it undoes all the hard work. If an unmet dependency occurs it should just error out so you know the ROCm build needs upgrading.

I searched a bit but most online info pertains to how to prevent *local* upgrades through `requirements.txt`, which is not good enough.

**Comment by lamikr** [comment]
Yes, locking of package would be really nice feature but I doupt it exist. (Unless one changes permissions under python site-packages...)

**Comment by jeroen-mostert** [comment]
The package freezing seems to be a no-go. Even permission changes don't really work because pip renames things. You can completely cripple pip by denying changes to whole package directory (or go superuser and use `chattr +i`) but that seems like unwanted overkill (and would need to be undone and redone every time *we* install).

Everyone just says "use a venv". There is something to say for that idea in that we could package a script for setting up venvs that automatically include frozen versions of our local site packages in `requirements.txt` (they're easily recognized in the `pip freeze` output). You would still need to remember to use that, though, so it's not necessarily much better than just invoking pip appropriately. "I really love the way Python handles software packaging and dependencies!" said no one ever.
