### ISSUE TITLE
`babs.sh -i` is broken in various ways for subdirs

### ISSUE THREAD

**Issue by jeroen-mostert** [lamikr/rocm_sdk_builder#120]
From a completely fresh build, doing `./babs.sh -i binfo/core/003_llvm_project_llvm.binfo` produces a source directory in `src_projects/llvm-project/llvm`. This causes the build to fail, because the project is *supposed* to be cloned into `src_projects/llvm-project`, where the `llvm` subdir is going to be provided by the upstream repo.

Doing `./babs.sh -i` without specifying the `binfo` produces something even stranger: a new empty `llvm-project` directory containing only `amd/device-libs` and `.git`, but without actually initializing and patching the repo. A subsequent `./babs.sh -co` will then fail.

**Comment by lamikr** [comment]
Damn... While I did the individual binfo file support to bash.sh, I have broken the support for BINFO_APP_SRC_CLONE_DIR variable that is in use for couple of projects where the build dir is not in the root but in the subfolder.  Unfortunately this has been broken at least for one week, fixis asap,
