### ISSUE TITLE
rocprofiler - roctracer order

### ISSUE THREAD

**Issue by jeroen-mostert** [lamikr/rocm_sdk_builder#121]
Here's an odd one I can't quite explain: on a fresh build on Void Linux, building rocprofiler fails if roctracer is not built first. In other words, the order needs to be swapped. Since this has been the order for a long time now, I can only guess something has changed upstream. Or maybe this is strictly due to me doing manual one-by-one builds, but I don't think babs does anything clever about the order. Maybe this normally doesn't happen because all the source inits happen before all the builds -- in that case a one-by-one build is a good way to catch these issues.

**Comment by lamikr** [comment]
I think the rocprofiler can be build first but during the build time it will need the roctracers source code.
In the rocprofiler binfo-file I define the location of roctracer headers in this way:

011_01_rocprofiler.binfo:BINFO_APP_CMAKE_CFG="${BINFO_APP_CMAKE_CFG} -DPROF_API_HEADER_PATH=${SDK_SRC_ROOT_DIR}/roctracer/inc/ext"

**Comment by jeroen-mostert** [comment]
Yeah, exactly. So if you don't init all the repos first, the build will fail. This didn't use to be possible, but since the extension where you can specify individual binfos it is. Since (AFAICT) roctracer can be built before rocprofiler, but not the other way around, these binfos (011_01 / 011_02) should arguably be swapped. We don't record dependencies of binfos to keep it simple, but then the minimum that should hold is that any lower number does not depend on any higher number even being present, including source. I think this is the only "wrong way around" dependency I encountered.
