### ISSUE TITLE
Typo in build/binfo_operations.sh

### ISSUE THREAD

**Issue by 2eQTu** [lamikr/rocm_sdk_builder#151]
Seems like the first line in `binfo_operations.sh` has a typo or copy paste error.   This file is only ever sourced elsewhere, so i guess the code still works fine.

https://github.com/lamikr/rocm_sdk_builder/blob/bfe49cdcb025c1f5de3a68c9a431d9a434c37447/build/binfo_operations.sh#L1

**Comment by lamikr** [comment]
This fix has been merged some time ago, closing.
