### ISSUE TITLE
Add support for Instinct MI100 (GFX908)

### ISSUE THREAD

**Issue by CuteSC2** [lamikr/rocm_sdk_builder#158]
Add support for the AMD Instinct MI100 

Branch:
https://github.com/CuteSC2/rocm_sdk_builder_advanced/tree/wip/rocm_sdk_builder_GFX908

Tasks:

- [ ] Add Accelerator to GPU selection
- [ ] ROCM support
- [ ] Triton support
- [ ] Pytorch support
- [ ] onnxRuntime support
- [ ] TensorFlow support
- [ ] Add HPC (64bit Vector) compute benchmark
- [ ] Add functionality tests for the MI100

**Comment by lamikr** [comment]
Hi, this sounds interesting, unfortunately I do not have myself acceess at least yet to MI-series of devices to test them. Running on Azure cloud could be one possibility but I do not have budget/access to do that at the moment.

**Comment by CuteSC2** [comment]
I'll have access to MI50 16/32GB and MI100 cards and add the support myself this winter, pr will come soon

**Comment by lamikr** [comment]
Thats cool!

**Comment by lamikr** [comment]
There should be now the experimental MI50/Vega7(gfx906) support and MI100 (gfx908) if you are able to test?
In addition there is now also patches to build the initial support for AMD Strix point and Strix halo. These are all just build tested as I do not have access to cards.

I am at the moment working for podman/dockericing these to help the testing but it would be great if you have time to try to build and test while I am working on for trying to find those cards somewhere for testing...
