### ISSUE TITLE
Extra binfo management

### ISSUE THREAD

**Issue by daniandtheweb** [lamikr/rocm_sdk_builder#166]
Continuing the discussion in #165.

As far as I know it's not currently possible to build stable-diffusion.cpp with the latest version of ggml, there's some work needed to upstream it as ggml develops quite fast.

I think it would be a great idea installing every extra binfo project in a separate directory, using source on env_rocm could then allow an easy access to them. This way it could also be easier to 'uninstall' any extra program with minimal effort.

**Comment by lamikr** [comment]
I here what you say. At some point it's likely that some kind of packaging is added and that could then work instead. At the moment I have thought that rebuilding each rocm sdk to different directory is enought.
But if it's ok, I will change the stable-diffusion install dir under /opt/rocm_sdk_612/apps?

just checked that llama.cpp install these from ggml headers:

[100%] Built target llama-q8dot
Install the project...
-- Install configuration: "Release"
-- Installing: /opt/rocm_sdk_612/lib64/libggml.so
-- Installing: /opt/rocm_sdk_612/include/ggml.h
-- Installing: /opt/rocm_sdk_612/include/ggml-alloc.h
-- Installing: /opt/rocm_sdk_612/include/ggml-backend.h
-- Installing: /opt/rocm_sdk_612/include/ggml-blas.h
-- Installing: /opt/rocm_sdk_612/include/ggml-cann.h
-- Installing: /opt/rocm_sdk_612/include/ggml-cuda.h
-- Installing: /opt/rocm_sdk_612/include/ggml.h
-- Installing: /opt/rocm_sdk_612/include/ggml-kompute.h
-- Installing: /opt/rocm_sdk_612/include/ggml-metal.h
-- Installing: /opt/rocm_sdk_612/include/ggml-rpc.h
-- Installing: /opt/rocm_sdk_612/include/ggml-sycl.h
-- Installing: /opt/rocm_sdk_612/include/ggml-vulkan.h
-- Up-to-date: /opt/rocm_sdk_612/lib64/libggml.so
-- Up-to-date: /opt/rocm_sdk_612/include/ggml.h
-- Up-to-date: /opt/rocm_sdk_612/include/ggml-alloc.h
-- Up-to-date: /opt/rocm_sdk_612/include/ggml-backend.h
-- Up-to-date: /opt/rocm_sdk_612/include/ggml-blas.h
-- Up-to-date: /opt/rocm_sdk_612/include/ggml-cann.h
-- Up-to-date: /opt/rocm_sdk_612/include/ggml-cuda.h
-- Up-to-date: /opt/rocm_sdk_612/include/ggml.h
-- Up-to-date: /opt/rocm_sdk_612/include/ggml-kompute.h
-- Up-to-date: /opt/rocm_sdk_612/include/ggml-metal.h
-- Up-to-date: /opt/rocm_sdk_612/include/ggml-rpc.h
-- Up-to-date: /opt/rocm_sdk_612/include/ggml-sycl.h
-- Up-to-date: /opt/rocm_sdk_612/include/ggml-vulkan.h
-- Installing: /opt/rocm_sdk_612/lib64/libllama.so
-- Set runtime path of "/opt/rocm_sdk_612/lib64/libllama.so" to ""
-- Up-to-date: /opt/rocm_sdk_612/include/llama.h
-- Up-to-date: /opt/rocm_sdk_612/lib64/cmake/llama/llama-config.cmake
-- Up-to-date: /opt/rocm_sdk_612/lib64/cmake/llama/llama-version.cmake
-- Up-to-date: /opt/rocm_sdk_612/bin/convert_hf_to_gguf.py
-- Up-to-date: /opt/rocm_sdk_612/lib/pkgconfig/llama.pc
-- Installing: /opt/rocm_sdk_612/bin/test-tokenizer-0

**Comment by daniandtheweb** [comment]
>  But if it's ok, I will change the stable-diffusion install dir under /opt/rocm_sdk_612/apps?
That's exactly what seems to be the best idea, having each extra project under its own directory inside of /opt/rocm_sdk_612/apps/...

I'm not entirely sure about the usefulness of the headers of llama.cpp. As you can see both stable-diffusion.cpp and llama.cpp build the same headers but from different ggml sources (llama.cpp's is always more updated) so I think that the best way to handle it would be to just install them in the project directory ( /opt/rocm_sdk_612/apps/llama.cpp, /opt/rocm_sdk_612/apps/stable-diffusion.cpp, ...).
I think that doing something like this could help avoiding any problems that could arise by mixing the headers.

**Comment by lamikr** [comment]
Yes, that's seems to be the best way. We could then create the symlink in post-install steps from /opt/rocm/bin/sd to /opt/rocm/apps/stable-diffusion-cpp/bin/sd

In ideal world ggml would be build in it's own package and stable-diffusion-cpp and llama.cpp would then just build agains it. Second best choise would be that it would be included as a gitsubmodule so one would always know which version of it is used. Unfortunately both projects seems to instead just include own implementation of ggml and neither is never exactly the same than the upstream ggml version.

So you may be right that llama.cpp should probably also be installed to under rocm_sdk_612/apps. And then maybe the upstream ggml would be the third one that could be useful on it's own also, This has been so far the best description I have seen: https://github.com/ggerganov/ggml/discussions/141
