### ISSUE TITLE
roctracer build failure

### ISSUE THREAD

**Issue by clustor** [lamikr/rocm_sdk_builder#176]
I have seletected only gfx1103 for building with rocm_sdk_612 and I get this linker failure. 

`/usr/bin/ld: CMakeFiles/MatrixTranspose_test.dir/app/MatrixTranspose_test_generated_MatrixTranspose_test.cpp.o: in function `main':
MatrixTranspose_test.cpp:(.text+0x322): undefined reference to `hipGetDevicePropertiesR0600'
/usr/bin/ld: CMakeFiles/MatrixTranspose_mgpu.dir/app/MatrixTranspose_mgpu_generated_MatrixTranspose_test.cpp.o: in function `main':
MatrixTranspose_test.cpp:(.text+0x360): undefined reference to `hipGetDevicePropertiesR0600'
/usr/bin/ld: CMakeFiles/MatrixTranspose_hipaact_test.dir/app/MatrixTranspose_hipaact_test_generated_MatrixTranspose_test.cpp.o: in function `main':
MatrixTranspose_test.cpp:(.text+0x322): undefined reference to `hipGetDevicePropertiesR0600'
/usr/bin/ld: CMakeFiles/MatrixTranspose.dir/hip/MatrixTranspose_generated_MatrixTranspose.cpp.o: in function `main':
MatrixTranspose.cpp:(.text+0x15c): undefined reference to `hipGetDevicePropertiesR0600'
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

Full log here. 

`make[2]: Leaving directory '/home/dev/src/rocm_sdk_builder/builddir/011_01_roctracer'
make  -f plugin/file/CMakeFiles/file_plugin.dir/build.make plugin/file/CMakeFiles/file_plugin.dir/build
make[2]: Entering directory '/home/dev/src/rocm_sdk_builder/builddir/011_01_roctracer'
make[2]: Nothing to be done for 'plugin/file/CMakeFiles/file_plugin.dir/build'.
make[2]: Leaving directory '/home/dev/src/rocm_sdk_builder/builddir/011_01_roctracer'
[ 86%] Built target file_plugin
HIP_PATH=/opt/rocm_sdk_612
HIP_PLATFORM=amd
HIP_COMPILER=clang
HIP_RUNTIME=rocclr
ROCM_PATH=/opt/rocm_sdk_612
HIP_ROCCLR_HOME=/opt/rocm_sdk_612
HIP_CLANG_PATH=/opt/rocm_sdk_612/bin
HIP_INCLUDE_PATH=/opt/rocm_sdk_612/include
HIP_LIB_PATH=/opt/rocm_sdk_612/lib
DEVICE_LIB_PATH=/opt/rocm_sdk_612/amdgcn/bitcode
HIP_CLANG_RT_LIB=/opt/rocm_sdk_612/lib/clang/17/lib/linux
hipcc-args: -no-pie -Wl,--build-id=md5 CMakeFiles/roctx_test.dir/app/roctx_test_generated_roctx_test.cpp.o -o roctx_test -Wl,-rpath,/home/dev/src/rocm_sdk_builder/builddir/011_01_roc
tracer: ../libroctx64.so.4.1.0
hipcc-cmd: "/opt/rocm_sdk_612/bin/clang" --driver-mode=g++ -O3 --hip-path="/opt/rocm_sdk_612" --hip-link --rtlib=compiler-rt -unwindlib=libgcc  -no-pie -Wl,--build-id=md5 CMakeFiles/roct
x_test.dir/app/roctx_test_generated_roctx_test.cpp.o -o "roctx_test" -Wl,-rpath,/home/dev/src/rocm_sdk_builder/builddir/011_01_roctracer\: ../libroctx64.so.4.1.0
HIP_PATH=/opt/rocm_sdk_612
HIP_PATH=/opt/rocm_sdk_612
HIP_PLATFORM=amd
HIP_PLATFORM=amd
HIP_COMPILER=clang
HIP_COMPILER=clang
HIP_RUNTIME=rocclr
HIP_RUNTIME=rocclr
HIP_PATH=/opt/rocm_sdk_612
HIP_PLATFORM=amd
HIP_COMPILER=clang
HIP_RUNTIME=rocclr
HIP_PATH=/opt/rocm_sdk_612
HIP_PLATFORM=amd                                                                                                                                                        18:57:50 [88/1880]
HIP_COMPILER=clang
HIP_RUNTIME=rocclr
HIP_PATH=/opt/rocm_sdk_612
HIP_PLATFORM=amd
HIP_COMPILER=clang
HIP_RUNTIME=rocclr
HIP_PATH=/opt/rocm_sdk_612
HIP_PLATFORM=amd
HIP_COMPILER=clang
HIP_RUNTIME=rocclr
ROCM_PATH=/opt/rocm_sdk_612
HIP_ROCCLR_HOME=/opt/rocm_sdk_612
HIP_CLANG_PATH=/opt/rocm_sdk_612/bin
HIP_INCLUDE_PATH=/opt/rocm_sdk_612/include
ROCM_PATH=/opt/rocm_sdk_612
HIP_LIB_PATH=/opt/rocm_sdk_612/lib
ROCM_PATH=/opt/rocm_sdk_612
HIP_ROCCLR_HOME=/opt/rocm_sdk_612
DEVICE_LIB_PATH=/opt/rocm_sdk_612/amdgcn/bitcode
ROCM_PATH=/opt/rocm_sdk_612
HIP_ROCCLR_HOME=/opt/rocm_sdk_612
HIP_CLANG_PATH=/opt/rocm_sdk_612/bin
HIP_CLANG_RT_LIB=/opt/rocm_sdk_612/lib/clang/17/lib/linux
HIP_ROCCLR_HOME=/opt/rocm_sdk_612
HIP_INCLUDE_PATH=/opt/rocm_sdk_612/include
HIP_CLANG_PATH=/opt/rocm_sdk_612/bin
HIP_CLANG_PATH=/opt/rocm_sdk_612/bin
HIP_LIB_PATH=/opt/rocm_sdk_612/lib
HIP_INCLUDE_PATH=/opt/rocm_sdk_612/include
HIP_INCLUDE_PATH=/opt/rocm_sdk_612/include
DEVICE_LIB_PATH=/opt/rocm_sdk_612/amdgcn/bitcode
HIP_CLANG_RT_LIB=/opt/rocm_sdk_612/lib/clang/17/lib/linux
HIP_LIB_PATH=/opt/rocm_sdk_612/lib
HIP_LIB_PATH=/opt/rocm_sdk_612/lib
DEVICE_LIB_PATH=/opt/rocm_sdk_612/amdgcn/bitcode
HIP_CLANG_RT_LIB=/opt/rocm_sdk_612/lib/clang/17/lib/linux
DEVICE_LIB_PATH=/opt/rocm_sdk_612/amdgcn/bitcode
hipcc-args: -no-pie -Wl,--build-id=md5 CMakeFiles/MatrixTranspose_test.dir/app/MatrixTranspose_test_generated_MatrixTranspose_test.cpp.o -o MatrixTranspose_test -Wl,-rpath,/home/dev/
src/rocm_sdk_builder/builddir/011_01_roctracer:/opt/rocm_sdk_612/lib64: ../libroctracer64.so.4.1.0 ../libroctx64.so.4.1.0 -Wl,-rpath-link,/opt/rocm_sdk_612/lib64
HIP_CLANG_RT_LIB=/opt/rocm_sdk_612/lib/clang/17/lib/linux
ROCM_PATH=/opt/rocm_sdk_612
hipcc-args: -no-pie -Wl,--build-id=md5 CMakeFiles/multi_pool_activities.dir/directed/multi_pool_activities_generated_multi_pool_activities.cpp.o -o multi_pool_activities -Wl,-rpath,/home
/dev/src/rocm_sdk_builder/builddir/011_01_roctracer:/opt/rocm_sdk_612/lib64: ../libroctracer64.so.4.1.0 -Wl,-rpath-link,/opt/rocm_sdk_612/lib64
HIP_ROCCLR_HOME=/opt/rocm_sdk_612
HIP_CLANG_PATH=/opt/rocm_sdk_612/bin
HIP_INCLUDE_PATH=/opt/rocm_sdk_612/include
hipcc-args: -no-pie -Wl,--build-id=md5 CMakeFiles/MatrixTranspose_mgpu.dir/app/MatrixTranspose_mgpu_generated_MatrixTranspose_test.cpp.o -o MatrixTranspose_mgpu -Wl,-rp18:57:50 [41/1880]
src/rocm_sdk_builder/builddir/011_01_roctracer:/opt/rocm_sdk_612/lib64: ../libroctracer64.so.4.1.0 ../libroctx64.so.4.1.0 -Wl,-rpath-link,/opt/rocm_sdk_612/lib64
HIP_LIB_PATH=/opt/rocm_sdk_612/lib
DEVICE_LIB_PATH=/opt/rocm_sdk_612/amdgcn/bitcode
HIP_CLANG_RT_LIB=/opt/rocm_sdk_612/lib/clang/17/lib/linux
ROCM_PATH=/opt/rocm_sdk_612
hipcc-args: -no-pie -Wl,--build-id=md5 CMakeFiles/MatrixTranspose_hipaact_test.dir/app/MatrixTranspose_hipaact_test_generated_MatrixTranspose_test.cpp.o -o MatrixTranspose_hipaact_test -
Wl,-rpath,/home/dev/src/rocm_sdk_builder/builddir/011_01_roctracer:/opt/rocm_sdk_612/lib64: ../libroctracer64.so.4.1.0 ../libroctx64.so.4.1.0 -Wl,-rpath-link,/opt/rocm_sdk_612/lib64
HIP_ROCCLR_HOME=/opt/rocm_sdk_612
HIP_CLANG_PATH=/opt/rocm_sdk_612/bin
HIP_INCLUDE_PATH=/opt/rocm_sdk_612/include
hipcc-args: -no-pie -Wl,--build-id=md5 CMakeFiles/activity_and_callback.dir/directed/activity_and_callback_generated_activity_and_callback.cpp.o -o activity_and_callback -Wl,-rpath,/home
/dev/src/rocm_sdk_builder/builddir/011_01_roctracer:/opt/rocm_sdk_612/lib64: ../libroctracer64.so.4.1.0 -Wl,-rpath-link,/opt/rocm_sdk_612/lib64
HIP_LIB_PATH=/opt/rocm_sdk_612/lib
DEVICE_LIB_PATH=/opt/rocm_sdk_612/amdgcn/bitcode
HIP_CLANG_RT_LIB=/opt/rocm_sdk_612/lib/clang/17/lib/linux
hipcc-args: -no-pie -Wl,--build-id=md5 CMakeFiles/MatrixTranspose.dir/hip/MatrixTranspose_generated_MatrixTranspose.cpp.o -o MatrixTranspose -Wl,-rpath,/home/dev/src/rocm_sdk_builder
/builddir/011_01_roctracer:/opt/rocm_sdk_612/lib64: ../libroctracer64.so.4.1.0 ../libroctx64.so.4.1.0 -Wl,-rpath-link,/opt/rocm_sdk_612/lib64
hipcc-cmd: "/opt/rocm_sdk_612/bin/clang" --driver-mode=g++ -O3 --hip-path="/opt/rocm_sdk_612" --hip-link --rtlib=compiler-rt -unwindlib=libgcc  -no-pie -Wl,--build-id=md5 CMakeFiles/Matr
ixTranspose_hipaact_test.dir/app/MatrixTranspose_hipaact_test_generated_MatrixTranspose_test.cpp.o -o "MatrixTranspose_hipaact_test" -Wl,-rpath,/home/dev/src/rocm_sdk_builder/builddi
r/011_01_roctracer\:/opt/rocm_sdk_612/lib64\: ../libroctracer64.so.4.1.0 ../libroctx64.so.4.1.0 -Wl,-rpath-link,/opt/rocm_sdk_612/lib64
hipcc-cmd: "/opt/rocm_sdk_612/bin/clang" --driver-mode=g++ -O3 --hip-path="/opt/rocm_sdk_612" --hip-link --rtlib=compiler-rt -unwindlib=libgcc  -no-pie -Wl,--build-id=md5 CMakeFiles/mult
i_pool_activities.dir/directed/multi_pool_activities_generated_multi_pool_activities.cpp.o -o "multi_pool_activities" -Wl,-rpath,/home/dev/src/rocm_sdk_builder/builddir/011_01_roctra
cer\:/opt/rocm_sdk_612/lib64\: ../libroctracer64.so.4.1.0 -Wl,-rpath-link,/opt/rocm_sdk_612/lib64
hipcc-cmd: "/opt/rocm_sdk_612/bin/clang" --driver-mode=g++ -O3 --hip-path="/opt/rocm_sdk_612" --hip-link --rtlib=compiler-rt -unwindlib=libgcc  -no-pie -Wl,--build-id=md5 CMakeFiles/Matr
ixTranspose.dir/hip/MatrixTranspose_generated_MatrixTranspose.cpp.o -o "MatrixTranspose" -Wl,-rpath,/home/dev/src/rocm_sdk_builder/builddir/011_01_roctracer\:/opt/rocm_sdk_612/lib64\
: ../libroctracer64.so.4.1.0 ../libroctx64.so.4.1.0 -Wl,-rpath-link,/opt/rocm_sdk_612/lib64
hipcc-cmd: "/opt/rocm_sdk_612/bin/clang" --driver-mode=g++ -O3 --hip-path="/opt/rocm_sdk_612" --hip-link --rtlib=compiler-rt -unwindlib=libgcc  -no-pie -Wl,--build-id=md5 CMakeFiles/Matr
ixTranspose_mgpu.dir/app/MatrixTranspose_mgpu_generated_MatrixTranspose_test.cpp.o -o "MatrixTranspose_mgpu" -Wl,-rpath,/home/dev/src/rocm_sdk_builder/builddir/011_01_roctracer\:/opt
/rocm_sdk_612/lib64\: ../libroctracer64.so.4.1.0 ../libroctx64.so.4.1.0 -Wl,-rpath-link,/opt/rocm_sdk_612/lib64
hipcc-cmd: "/opt/rocm_sdk_612/bin/clang" --driver-mode=g++ -O3 --hip-path="/opt/rocm_sdk_612" --hip-link --rtlib=compiler-rt -unwindlib=libgcc  -no-pie -Wl,--build-id=md5 CMakeFiles/acti
vity_and_callback.dir/directed/activity_and_callback_generated_activity_and_callback.cpp.o -o "activity_and_callback" -Wl,-rpath,/home/dev/src/rocm_sdk_builder/builddir/011_01_roctra
cer\:/opt/rocm_sdk_612/lib64\: ../libroctracer64.so.4.1.0 -Wl,-rpath-link,/opt/rocm_sdk_612/lib64
hipcc-cmd: "/opt/rocm_sdk_612/bin/clang" --driver-mode=g++ -O3 --hip-path="/opt/rocm_sdk_612" --hip-link --rtlib=compiler-rt -unwindlib=libgcc  -no-pie -Wl,--build-id=md5 CMakeFiles/Matr
ixTranspose_test.dir/app/MatrixTranspose_test_generated_MatrixTranspose_test.cpp.o -o "MatrixTranspose_test" -Wl,-rpath,/home/dev/src/rocm_sdk_builder/builddir/011_01_roctracer\:/opt
/rocm_sdk_612/lib64\: ../libroctracer64.so.4.1.0 ../libroctx64.so.4.1.0 -Wl,-rpath-link,/opt/rocm_sdk_612/lib64
make[2]: Leaving directory '/home/dev/src/rocm_sdk_builder/builddir/011_01_roctracer'
[ 88%] Built target roctx_test
/usr/bin/ld: CMakeFiles/MatrixTranspose_test.dir/app/MatrixTranspose_test_generated_MatrixTranspose_test.cpp.o: in function `main':
MatrixTranspose_test.cpp:(.text+0x322): undefined reference to `hipGetDevicePropertiesR0600'
/usr/bin/ld: CMakeFiles/MatrixTranspose_mgpu.dir/app/MatrixTranspose_mgpu_generated_MatrixTranspose_test.cpp.o: in function `main':
MatrixTranspose_test.cpp:(.text+0x360): undefined reference to `hipGetDevicePropertiesR0600'
/usr/bin/ld: CMakeFiles/MatrixTranspose_hipaact_test.dir/app/MatrixTranspose_hipaact_test_generated_MatrixTranspose_test.cpp.o: in function `main':
MatrixTranspose_test.cpp:(.text+0x322): undefined reference to `hipGetDevicePropertiesR0600'
/usr/bin/ld: CMakeFiles/MatrixTranspose.dir/hip/MatrixTranspose_generated_MatrixTranspose.cpp.o: in function `main':
MatrixTranspose.cpp:(.text+0x15c): undefined reference to `hipGetDevicePropertiesR0600'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: Leaving directory '/home/dev/src/rocm_sdk_builder/builddir/011_01_roctracer'
make[2]: *** [test/CMakeFiles/MatrixTranspose_test.dir/build.make:427: test/MatrixTranspose_test] Error 1
make[2]: Leaving directory '/home/dev/src/rocm_sdk_builder/builddir/011_01_roctracer'
make[1]: *** [CMakeFiles/Makefile2:577: test/CMakeFiles/MatrixTranspose_test.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** [test/CMakeFiles/MatrixTranspose_hipaact_test.dir/build.make:427: test/MatrixTranspose_hipaact_test] Error 1
make[2]: Leaving directory '/home/dev/src/rocm_sdk_builder/builddir/011_01_roctracer'
make[1]: *** [CMakeFiles/Makefile2:604: test/CMakeFiles/MatrixTranspose_hipaact_test.dir/all] Error 2
make[2]: *** [test/CMakeFiles/MatrixTranspose_mgpu.dir/build.make:427: test/MatrixTranspose_mgpu] Error 1
make[2]: Leaving directory '/home/dev/src/rocm_sdk_builder/builddir/011_01_roctracer'
make[1]: *** [CMakeFiles/Makefile2:631: test/CMakeFiles/MatrixTranspose_mgpu.dir/all] Error 2
make[2]: *** [test/CMakeFiles/MatrixTranspose.dir/build.make:392: test/MatrixTranspose] Error 1
make[2]: Leaving directory '/home/dev/src/rocm_sdk_builder/builddir/011_01_roctracer'
make[1]: *** [CMakeFiles/Makefile2:550: test/CMakeFiles/MatrixTranspose.dir/all] Error 2
[ 90%] Built target activity_and_callback
make[2]: Leaving directory '/home/dev/src/rocm_sdk_builder/builddir/011_01_roctracer'
[ 92%] Built target multi_pool_activities
make[1]: Leaving directory '/home/dev/src/rocm_sdk_builder/builddir/011_01_roctracer'
make: *** [Makefile:156: all] Error 2
build failed: roctracer`

**Comment by lamikr** [comment]
Hi, which Linux distro you are using?

**Comment by clustor** [comment]
Hi, I figured this out by doing `strace` on `ld`. I had rocm-5.7 installed. Before hipcc got a chance to look at /opt/rocm_sdk_612/lib for libamdhip64.so, it found the file in /lib/x86_64-linux-gnu from rocm-5.7. After I uninstalled, it built fine.

**Comment by clustor** [comment]
Btw, thank you so much for this project. This made it lot easy.
