### ISSUE TITLE
gfx803 support

### ISSUE THREAD

**Issue by tuleo1** [lamikr/rocm_sdk_builder#31]
:c any hopes for the gfx803 to be supported and be built for?

**Comment by lamikr** [comment]
Sorry for not answering this one. At the moment I do not have resources to test gfx803 by myself. It's and old card but basic support should still be doable as lot of code base has anyway detection for it. Have you tried to select gfx803 from the configure and checked if the build proceeds with it?

**Comment by tuleo1** [comment]
not exactly. I tried building using the latest release and from the selection there was no way of actually selecting gfx803. and I didn't bother with going on the older versions to try and build.
I thought maybe I could ask here.
I can try to manually add and select gfx803... although unsure how would that end up being

**Comment by lamikr** [comment]
I close this for now as it may be too hard to start fully supporting gfx803 with rocm sdk builder.
In principle the build could work at least for hip and opencl examples by entering manually the line

    gfx803

to user_build.cfg file and then doing a build with ./babs.sh -b
