### ISSUE TITLE
torch_migraphx won't build with /home/<user>/.local/bin/cmake

### ISSUE THREAD

**Issue by Stefan-Olt** [lamikr/rocm_sdk_builder#41]
I have a cmake installed installed using pip in my user dir (because the one of my Linux Mint 21 (Ubuntu 22.04) is too old for many projects), torch_migraphx fails to compile with it. Renaming it fixed the problem. For onnx I had to rename it back, otherwise that wouldn't work.
Doesn't the project come with it it's own cmake that should be used?

**Comment by lamikr** [comment]
It builds own python version, boost and zstd which I found not being stable/similar enought between distributions but from cmake it still uses the disrto version. I have just now created myself and mint 21 on virtual machine and just installed all the same debs than for ubuntu. So I can try to verify your changes if you want to send patches?

I try to avoid the mold build however if possible. It would be nice to get mint 21/ubuntu 22.04 of working even if never release is available.

**Comment by lamikr** [comment]
I included cmake 3.26.6 version to the build now. At the moment only the Deepspeed project build script has a test of cmake and will take this one in use if needed. (Ubuntu 22.04 ships 3.21 version of cmake and DeepSpeed rquires 3.26. Other projects included on rocm_sdk_builder works ok with default cmake version that distro offers. (Mageia 9, Fedora 40, Linux Mint 21, Ubuntu 24.04 tested)
