### ISSUE TITLE
Add tested distribution versions to document/readme.md

### ISSUE THREAD

**Issue by lamikr** [lamikr/rocm_sdk_builder#44]
Mageia 9, Ubuntu 23.10, Ubuntu 24.04, Fedora 39, Fedora 40, Arch Linux (which version?), Manjaro Linux (which version?), ?

MintLinux 22.04 testing/patching ongoing...

**Comment by daniandtheweb** [comment]
Arch and Manjaro are rolling releases so there's no specific version that can be used.

**Comment by lamikr** [comment]
Ok, thats good inform to know. Are you able to send what they have in /etc/os-release files?

**Comment by daniandtheweb** [comment]
This is the full os-releases for Manjaro:
```
NAME="Manjaro Linux"
PRETTY_NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://forum.manjaro.org/"
BUG_REPORT_URL="https://docs.manjaro.org/reporting-bugs/"
PRIVACY_POLICY_URL="https://manjaro.org/privacy-policy/"
LOGO=manjarolinux
``` 
Here's the content for /etc/lsb-release:
```
DISTRIB_ID="ManjaroLinux"
DISTRIB_RELEASE="24.0.1"
DISTRIB_CODENAME="Wynsdey"
DISTRIB_DESCRIPTION="Manjaro Linux"
```

**Comment by jeroen-mostert** [comment]
Manjaro's release number applies to the stable branch, which is not as rolling as the main Arch and Manjaro branches are. For test and unstable this number isn't relevant. "Full" Manjaro support might take it into account for those folks who run Manjaro specifically to have a more stable Arch, but I doubt those are the target audience for ROCm, as GPU drivers are very much a moving target and you'll always want the latest bits.

**Comment by lamikr** [comment]
- Distros are now documented in updated readme.md better. Closing this now.
