### ISSUE TITLE
Collection of pytorch gpu benchmark results

### ISSUE THREAD

**Issue by lamikr** [lamikr/rocm_sdk_builder#63]
Extensive GPU benchmarks with AMD gpus can now be run by following steps after building the rocm sdk. This version has now been synced with the upstream version which has fixed the pytorch 2.0 support in another way I had done earlier and it runs all the tests without running exceptions.

```
git clone https://github.com/lamikr/pytorch-gpu-benchmark
cd pytorch-gpu-benchmark
source /opt/rocm_sdk_611/bin/env_rocm.sh
./test.sh

```

It would be nice to collect results from different computers and create some comparison graphs. 
On my AMD RX 6800 test execution was about 50 minutes and results were saved to 
result-folder to following 8 files.

```
'AMD Radeon RX 6800_1_gpus__double_model_inference_benchmark.csv'  'AMD Radeon RX 6800_1_gpus__half_model_inference_benchmark.csv'
'AMD Radeon RX 6800_1_gpus__double_model_train_benchmark.csv'      'AMD Radeon RX 6800_1_gpus__half_model_train_benchmark.csv'
'AMD Radeon RX 6800_1_gpus__float_model_inference_benchmark.csv'    config.json
'AMD Radeon RX 6800_1_gpus__float_model_train_benchmark.csv'        system_info.txt

```

I have stored those from my benchmark run now to results/AMD_Radeon_RX_6800 folder of gpu benchmark.

So if you have done the tests, can you send them as a pull requests. At the moment the plot.ipynb code which should read the CSV files and generate pictures seems to be broken so that needs to be fixed...

**Comment by eitch** [comment]
Hi @lamikr I've added my tests: https://github.com/ryujaehun/pytorch-gpu-benchmark/pull/31

Should i send the PR to your fork?

**Comment by eitch** [comment]
I now also sent the PR to your fork. I sure hope someone can fix the plotting.

**Comment by lamikr** [comment]
Thanks eitch, I noticed your 7900 xtx benchmarks today and merged the results to that repo.

Another tests I run quite often to check is vit example from this repo
https://github.com/BrianPulfer/PapersReimplementations.git (dir src/cv/vit)
and docs in
https://medium.com/@brianpulfer/vision-transformers-from-scratch-pytorch-a-step-by-step-guide-96c3313c2e0c

Then this one should contain all kind of usefull things

https://github.com/ROCm/ROCmValidationSuite/blob/master/docs/ug1main.md

**Comment by lamikr** [comment]
I have not integrated the tensorflow back, it's debugging is so time consuming if something goes wrong as it always like to trigger rebuild of everything without allowing to just fix a thing and continue. But it's tensorboard seems to be possible to install separately with pip install and at least that could provide some easy to use gui if writing tests that logs data.

**Comment by lamikr** [comment]
pytorch gpu benchmark can now run tests for each gpu separately and/or using all gpus togetger in multi-gpu systems.
(See now -i option in addition of -g option)

**Comment by lamikr** [comment]
I wrote small python plotter to show the benchmark results... Non suprisingly the 7900 XTX from @eitch leads...

![pytorch_gpu_benchmark](https://github.com/user-attachments/assets/dc55e4a5-500a-454a-831d-a76faadd322b)

**Comment by lamikr** [comment]
Benchmark result pictures can now be generated pretty easil modifying the list of files that are selected to benchmark in

`plot_benchmark_results.py`

```
_result_filename_arr = [
                "results/AMD/AMD_Radeon_RX_7700S/AMD_Radeon_RX_7700S__half_model_train_benchmark.csv",
                "results/Nvidia/GeForce_GTX_1080_TI/GeForce_GTX_1080_TI__half_model_training_benchmark.csv",

```

And then running them by launching the

`./show_benchmark_results.sh`

https://github.com/lamikr/pytorch-gpu-benchmark/

**Comment by lamikr** [comment]
I added simple smokecheck benchmarks to benchmark directory. Will try to use these first to detect whether
the aotriton update to version with gfx11* series flashattention update and gfx11-series gpu tuning data speedups things

**Comment by lamikr** [comment]
Benchmark is now mentioned well with graph included on README.md. Closing this now.
