### ISSUE TITLE
6.1.2 - 025_01_hipBLAS.binfo references rocm_sdk_611

### ISSUE THREAD

**Issue by jrl290** [lamikr/rocm_sdk_builder#77]
Version 6.1.2 - [025_01_hipBLAS.binfo](https://github.com/lamikr/rocm_sdk_builder/blob/master/binfo/025_01_hipBLAS.binfo) contains this line

`BINFO_APP_CMAKE_CFG="${BINFO_APP_CMAKE_CFG} -DCMAKE_PREFIX_PATH=${INSTALL_DIR_PREFIX_SDK_ROOT}/lib64/cmake;${INSTALL_DIR_PREFIX_SDK_ROOT}/lib/cmake;/opt/rocm_sdk_611/gtest/lib64/cmake"`

Causing gtest libraries to not be found on build

**Comment by lamikr** [comment]
@jrl290 Thanks for spotting this, there were 3 places if fixed and pushed changes in.
- 001_rocm_core (env_rocm.sh had one 611 reference to opencl driver path)
- 025_hipBLAS
- 034_MIOpen

@jrl290 After you git pull the latest fixes,  You need to rebuild rocm_core to get opencl path fixed to the env_rocm.sh script. You can do that with commands:

```
rm -rf builddir/001_rocm_core/
./babs.sh -b

```
I will backport some of these fixes also to 611 branch.
