### ISSUE TITLE
LLVM default triple

### ISSUE THREAD

**Issue by jeroen-mostert** [lamikr/rocm_sdk_builder#87]
This is a small thing, but:

https://github.com/lamikr/rocm_sdk_builder/blob/ab9cf3147dc9974cad78ccfac0214e0aa53b9024/binfo/003_llvm_project_llvm.binfo#L21

Although explicitly referencing `mageia` is obviously fine for the owner of this repo :) and it seems to cause no difficulties on other distros since the relevant part is `x86_64`, wouldn't it make more sense to use `x86_64-unknown-linux-gnu` here? The explicit reference to `mageia` at the very least looks weird in build commands.

**Comment by lamikr** [comment]
Yes, I think it's time to remove that Mageia reference. It used to be more importance than nowadays when building the base system. Wondering could it be renamed even to something like "x86_64-rocm-linux-gnu" without breaking anything or parsed from the distributions "gcc -v" output.

**Comment by jeroen-mostert** [comment]
The `gcc -dumpmachine` output on my machine is `x86_64-pc-linux-gnu`, but digging a bit more I can find (e.g.) a default target for rust being `x86_64-unknown-linux-gnu`, and that seemed like a saner default. I expect it makes no actual difference. Parsing it from the build system seems wrong/unnecessary, however, since clang should already default to that. I thought the explicit mention of the triple was for the case of a VM build where people wanted to transfer all binaries (including the x86_64 clang) to a production system (where the VM might possibly be an ARM machine, for example).

**Comment by jeroen-mostert** [comment]
If I can hijack this a bit, am I right in assuming GH sends no mail on being mentioned in a discussion? I tagged you in https://github.com/lamikr/rocm_sdk_builder/discussions/85. I figured a discussion was the right way to go about that question, rather than opening an issue.

**Comment by lamikr** [comment]
Usually somewhere in the low level of glibc, gcc, linkers, etc. can be some distro specific optimizations and linker flags for default behavior. For example is user specifies the linker dir /usr/lib64, it could try to search the libraries in addition from the /usr/lib64/x86-64-mageia-linux directory for example or do something else distro specific.

(low-level libs used to have this type of if-defs for fedora, debian and slackware and other distros then patched same type of logic to their distro specific gcc rpm, binutil, linker or glibc rpm for example)

**Comment by jeroen-mostert** [comment]
I'm not sure on why the clang we custom build doesn't simply take its default triple from the host system, then -- if I omit the setting I get a build with `x86_64-unknown-linux-gnu`, even though my native `clang -dumpmachine` produces `x86_64-pc-linux-gnu`. Still, since the clang we custom build should get its entire environment from the ROCm "distro" you're right in that we can use either a custom triple, or a generic one. A generic one is probably still better for compatibility since presumably nothing will recognize `rocm`, and while nothing *should* fail on this, there's probably nothing to be gained from taking a risk either.

**Comment by lamikr** [comment]
Somehow I like more from the x86_64-pc-linux-gnu than unknown unknown because the can be even unknown unknown that nobody knows is unknown. Or something like that, idea was not mine, it just came to my mind from some unknown reason. So patch to change this to "x86_64-pc-linux-gnu" ?

**Comment by jeroen-mostert** [comment]
To get super technical, `x86_64-pc-linux-gnu` specifically designates an IBM PC compatible, while `unknown` does not. I'm not gonna say that no machines exist that run x86-64 Linux/GNU and are *not* IBM PC compatible, but they sure must be rare. :P Projects like rust probably settled on `x86_64-unknown-linux-gnu` because they also build on more esoteric configurations. I think that all (or almost all) things that do anything with the machine designation would know how to handle either.

**Comment by jeroen-mostert** [comment]
I don't intend to submit a formal pull for this, btw, when you have settled on your favorite triple, feel free to just slide it in with any commit you see fit. :P I can only confirm that `x86_64-unknown-linux-gnu` (what you get with no configured triple) builds and runs on Manjaro, but that says very little.

**Comment by lamikr** [comment]
Ok, I do a clean build and test the name change + upstream triton addition + your torch vision ffmgeg7 thing.

**Comment by jeroen-mostert** [comment]
Well I don't particularly love these either, but I didn't establish the naming of these things. :P If we had a time machine we could go back and make sure that instead of `unknown` we had `generic`, which is what it really means. Again, given the flexibility of these names and what tools have to do to handle them I'm sure `x86-64-banana-linux-tricycle` is probably processed correctly too. Well, maybe the `tricycle` could cause problems, but I'm sure the `banana` is OK...

**Comment by lamikr** [comment]
My first build with name change failed on Mageia for rocPRIM failing to find some libraries. I was in hurry, so did not have time to debug further. So I took this name change away and restarted a new patch with triton + your ffmpeg7 patch in. Will do similar build just in case also on fedora before applying the patches.

**Comment by jeroen-mostert** [comment]
Strange that `mageia` would happen to work out correctly on all distros, then, even if they're not Mageia. Maybe it's Mageia specifically that needs it (or maybe distros too that we just haven't seen yet).

**Comment by lamikr** [comment]
I had to test it more now. There seems to be at least 2 Mageia issues where gcc 12 /ld from Mageia behaves little differently.

1) ld linker library search path when it tries to link libraries and those libraries itself have dependencies to other libraries. Searching of those libraries is not controlled by "-L" but instead by "-Wl,-rpath-link". And if the triple is not "x86_64-mageia-linux", then the /usr/lib64 does not get inclued by default to "-Wl,-rpath-link". In other distros it seems to be. I tested that this I could easily patch to LDFLAGS in binfo/envsetup by adding there the -Wl,rpath-link. This is described in here: http://www.kaizou.org/2015/01/linux-libraries.html

Before the change, I got these type of errors:

```
    /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_995fd.dir/link.txt --verbose=1
    /opt/rocm_sdk_612/bin/hipcc -L/opt/rocm_sdk_612/lib64 -L/opt/rocm_sdk_612/lib -L/opt/rocm_sdk_612/hsa/lib -L/opt/rocm_sdk_612/rocblas/lib -L/opt/rocm_sdk_612/hcc/lib  CMakeFiles/cmTC_995fd.dir/testCXXCompiler.cxx.o -o cmTC_995fd 
    HIP_PATH=/opt/rocm_sdk_612
    HIP_PLATFORM=amd
    HIP_COMPILER=clang
    HIP_RUNTIME=rocclr
    ROCM_PATH=/opt/rocm_sdk_612
    HIP_ROCCLR_HOME=/opt/rocm_sdk_612
    HIP_CLANG_PATH=/opt/rocm_sdk_612/bin
    HIP_INCLUDE_PATH=/opt/rocm_sdk_612/include
    HIP_LIB_PATH=/opt/rocm_sdk_612/lib
    DEVICE_LIB_PATH=/opt/rocm_sdk_612/amdgcn/bitcode
    HIP_CLANG_RT_LIB=/opt/rocm_sdk_612/lib/clang/17/lib/linux
    hipcc-args: -L/opt/rocm_sdk_612/lib64 -L/opt/rocm_sdk_612/lib -L/opt/rocm_sdk_612/hsa/lib -L/opt/rocm_sdk_612/rocblas/lib -L/opt/rocm_sdk_612/hcc/lib CMakeFiles/cmTC_995fd.dir/testCXXCompiler.cxx.o -o cmTC_995fd
    hipcc-cmd: "/opt/rocm_sdk_612/bin/clang" --driver-mode=g++ -O3 --hip-path="/opt/rocm_sdk_612" --hip-link --rtlib=compiler-rt -unwindlib=libgcc  -L/opt/rocm_sdk_612/lib64 -L/opt/rocm_sdk_612/lib -L/opt/rocm_sdk_612/hsa/lib -L/opt/rocm_sdk_612/rocblas/lib -L/opt/rocm_sdk_612/hcc/lib CMakeFiles/cmTC_995fd.dir/testCXXCompiler.cxx.o -o "cmTC_995fd"
    /usr/lib/gcc/x86_64-linux-gnu/12/../../../../x86_64-linux-gnu/bin/ld: warning: libamd_comgr.so.2, needed by /opt/rocm_sdk_612/lib64/libamdhip64.so, not found (try using -rpath or -rpath-link)
    /usr/lib/gcc/x86_64-linux-gnu/12/../../../../x86_64-linux-gnu/bin/ld: warning: libhsa-runtime64.so.1, needed by /opt/rocm_sdk_612/lib64/libamdhip64.so, not found (try using -rpath or -rpath-link)
    /usr/lib/gcc/x86_64-linux-gnu/12/../../../../x86_64-linux-gnu/bin/ld: warning: libnuma.so.1, needed by /opt/rocm_sdk_612/lib64/libamdhip64.so, not found (try using -rpath or -rpath-link)
    /usr/lib/gcc/x86_64-linux-gnu/12/../../../../x86_64-linux-gnu/bin/ld: /opt/rocm_sdk_612/lib64/libamdhip64.so: undefined reference to `hsa_amd_vmem_map@ROCR_1'

```

2) Mageia's gcc uses the triple to search some gcc's internal include files located in
/include/c++/12/x86_64-mageia-linux/

After fixing problem 1 and the changed triple caused these type of problems:

```
In file included from /home/lamikr/own/rocm/src/sdk/rocm_sdk_builder_612/src_projects/rocprofiler/src/util/hsa_rsrc_factory.cpp:27:
/usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/cxxabi.h:50:10: fatal error: 'bits/cxxabi_tweaks.h' file not found
   50 | #include <bits/cxxabi_tweaks.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~
In file included from /home/lamikr/own/rocm/src/sdk/rocm_sdk_builder_612/src_projects/rocprofiler/test/util/hsa_rsrc_factory.cpp:27:
/usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/cxxabi.h:50:10: fatal error: 'bits/cxxabi_tweaks.h' file not found
   50 | #include <bits/cxxabi_tweaks.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~
1 error generated when compiling for gfx1030

```
For this one I do not have easy solution except to keep the triple in Mageia case the mageia one. For other distros I think we could change it. I can do that by identifying the distro in envsetup.sh
